language: ruby
rvm:
  - 2.4

env:
  global:
  - ENCRYPTION_LABEL: afb3f4a0fd37
  - COMMIT_AUTHOR_EMAIL: banerjs@banerjs.com

branches:
  except:
  - master

before_install:
  - openssl aes-256-cbc -K $encrypted_afb3f4a0fd37_key -iv $encrypted_afb3f4a0fd37_iv -in scripts/deploy_key.enc -out deploy_key -d
  - sudo apt-get update -qq
  - sudo apt-get install -qq rsync

install:
  - bundle install

script:
  - bundle exec jekyll build
  - bash scripts/deploy.sh
