language: ruby
rvm:
  - 2.4

env:
  global:
  - ENCRYPTION_LABEL: afb3f4a0fd37
  - COMMIT_AUTHOR_EMAIL: banerjs@banerjs.com

branches:
  only:
  - devel

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y rsync wget texlive-full

install:
  - bundle install

script:
  - bundle exec jekyll build
  - bash scripts/deploy.sh
