language: ruby
rvm:
  - 2.2
  - 2.4

env:
  global:
    - ENCRYPTION_LABEL: "2aabbcf4605b"
    - COMMIT_AUTHOR_EMAIL: "banerjs@banerjs.com"

branches:
  except:
    - master

before_install:
  - echo $(pwd)
  - openssl aes-256-cbc -K $encrypted_2aabbcf4605b_key -iv $encrypted_2aabbcf4605b_iv -in scripts/deploy_key.enc -out deploy_key -d
  - sudo apt-get update -qq
  - sudo apt-get install -qq rsync

install:
  - bundle install

script:
  - bash scripts/deploy.sh
