env:
  global:
  - ENCRYPTION_LABEL: afb3f4a0fd37
  - COMMIT_AUTHOR_EMAIL: banerjs@banerjs.com

sudo: required

services:
  - docker

git:
  depth: 10

branches:
  only:
  - devel

before_install:
  - docker pull banerjs/banerjs.github.io:builder

install:
  - docker run --rm -v $(pwd):/usr/src banerjs/banerjs.github.io:builder bash scripts/build_latex.sh
  - bundle install
  - bundle exec jekyll build

script:
  - bash scripts/deploy.sh
